### ISSUE TITLE
Will not convert test data

### ISSUE THREAD

**Issue by newmanw** [tmcw/twogeojson#1]
I am trying to convert your test data to geojson and having problems:

   var parser = tj.kml;
   var json = parser.sync(fs.readFileSync('extended_data.kml'));
   ... output missing all values

my output JSON file is:

   {"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":null}]}

**Comment by tmcw** [comment]
Closing - I'm deprecating twogeojson and recommending ogr for that size of file.
